# Site settings
title: Robert Jenssen | Webbutvecklare

# Content
name: Robert Jenssen
jobtitle: Webbutvecklare

# Social
github: Jenssen
instagram: jenssen_

# Contact
email: "robert@jenssen.me"

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]
